pull_request_rules:
  - name: automatic merge on CI success and review cipher1024
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#changes-requested-reviews-by=0"
      - base=master
      - label=ready-to-merge
      - approved-reviews-by=cipher1024
    actions:
      comment:
        message: 'yay'
  - name: automatic merge on CI success and review rwbarton
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#changes-requested-reviews-by=0"
      - base=master
      - label=ready-to-merge
      - approved-reviews-by=rwbarton
    actions:
      comment:
        message: 'yay'
  - name: automatic merge on CI success and review ChrisHughes24
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#changes-requested-reviews-by=0"
      - base=master
      - label=ready-to-merge
      - approved-reviews-by=ChrisHughes24
    actions:
      comment:
        message: 'yay'
