- name: automatic merge on CI success and review
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#changes-requested-reviews-by=0"
      - base=master
      - label=ready-to-merge
      - approved-reviews-by=['avigad','rwbarton','digama0','cipher1024','ChrisHughes24','robertylewis','patrickmassot']
    actions:
      delete_head_branch: {}
      merge:
        method: squash
        strict: smart
        strict_method: merge
