pull_request_rules:
  - name: automatic merge on CI success and label
  #If a PR has been labelled 'ready to merge', and the CI
  #test has passed against the most recent master,
  #the PR will be merged automatically, and the PR branch will be
  #deleted
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - base=master
      - label=ready-to-merge
    actions:
      delete_head_branch: {}
      merge:
        method: squash
        strict: smart
        strict_method: squash
  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews:
        approved: True
      label:
        remove: ready-to-merge
