pull_request_rules:
  - name: automatic merge with strict
    conditions:
      - base=master
    actions:
      merge:
        method: squash
        strict: true
      comment:
        message: "test"
